version: '3'

services:
    backend:
        container_name: backend_financial
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: financial
            DB_USERNAME: root
            DB_PASSWORD: root
        ports: 
            - 8000:8000
        volumes:
            - ./backend:/var/www
        depends_on:
            - db
        networks:
            - app
        restart: unless-stopped

    frontend:
        container_name: frontend_financial
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
        networks:
            - app
        restart: unless-stopped

    db:
        container_name: base_mysql
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: financial
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        networks:
            - app

        volumes:
            - dbdata:/var/lib/mysql
        restart: unless-stopped

networks:
    app:
        driver: bridge

volumes:
    dbdata:


